name: Code Test

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with code coverage
        run: yarn test

      - name: Upload coverage data
        uses: coverallsapp/github-action@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
